name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi-publish
    permissions:
      id-token: write # Required for trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: '>1.21'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --dev

      - name: Build package
        run: uv build

      - name: Check package
        run: uv run twine check dist/*

      - name: Install mcp tool for packaged version testing
        run: |
          GOBIN=$HOME/.local/bin go install \
            github.com/f/mcptools/cmd/mcptools@v0.7.1
          ln -s $HOME/.local/bin/mcptools $HOME/.local/bin/mcpt

      - name: Test packaged version
        run: |
          bash tests/packaging/test_packaged_version.sh

      - name: Publish to Test PyPI
        if: github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: Publish to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
